### PR TITLE
Add optional `socketpair` function for bidirectional pipes.

### PR DESCRIPTION
**Pull request by vi**

### CODE REVIEW

**Comment by arcnmx** [comment]
Neat, thanks! The name `socketpair` seems a bit misleading to me though, my first thought was that it implies the backing pipe is actually `std::os::unix::net::UnixStream::pipe()` instead. Maybe `bipipe()` or something more along those lines?

**Comment by vi** [comment]
Renamed.

**Comment by arcnmx** [comment]
Sorry this took so long to get to, although I will likely remove the feature from `default` due to it pulling in an additional dependency.

`resize-slice` is an extension trait for the slice primitive that allows in-place truncation/subslicing/etc. The main advantage/purpose of it is for modifying mutable slices in loops, which have borrow checker issues that are being solved eventually via non-lexical lifetimes: https://play.rust-lang.org/?gist=ce92dfd5627260f9e9a0520dd09052d5&version=nightly&mode=debug&edition=2015 - note how it doesn't work in stable/etc without NLL. This does however work in stable if you use `{}` to force the move as long as it's not in a loop.

**Comment by vi** [comment]
Shall there be

```toml
[package.metadata.docs.rs]
features = [ "bidirectional" ]
```

to show the function on docs.rs?

**Pull request merged**
